/**
 * WordsGenerator.java
 * 
 * Created on 21.09.2014
 */

package net.slightlymagic.laterna.oracle.tools;


import java.io.IOException;
import java.io.PrintStream;
import java.util.Iterator;
import java.util.Set;
import java.util.TreeSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import net.slightlymagic.laterna.oracle.grammar.WordMapping;
import net.slightlymagic.laterna.oracle.tools.Oracle.Ability;


/**
 * <p>
 * {@code WordsGenerator}
 * </p>
 * 
 * @version V0.0 21.09.2014
 * @author SillyFreak
 */
public class WordsGenerator {
    private static Pattern word = Pattern.compile("(~'s)|(\\{\\w+(?:/\\w+)*\\})|(\\p{IsLetter}+(?:'\\p{IsLetter}+)*'?)");
    
    public static void main(String[] args) throws IOException {
        Oracle content = AbilityExtractor.readSer();
        Set<String> words = new TreeSet<String>();
        StringBuffer sb = new StringBuffer();
        for(Ability a:content.abilities.values()) {
            matchWords(words, sb, a.text, false);
        }
        matchExtras(words, sb);
        
//        try (PrintStream out = System.out;) {
        try (PrintStream out = new PrintStream("src/main/antlr4/imports/Words.g4");) {
            out.println("lexer grammar Words;");
            out.println("//this file was generated by " + WordsGenerator.class.getName());
            out.println();
            out.println("tokens {");
            Set<String> ids = new TreeSet<String>();
            for(Iterator<String> it = words.iterator(); it.hasNext();) {
                String w = it.next();
                String id = WordMapping.getIdForWord(w);
//                String str = w.replaceAll("'", "\\\\'");
                if(!ids.add(id)) System.err.println("duplicate id: " + id);
//                out.printf("%s: '%s';%n", id, str);
                out.printf("  %s%s //%s%n", id, it.hasNext()? ',':' ', w);
            }
            out.println("}");
        }
    }
    
    private static void matchExtras(Set<String> words, StringBuffer sb) {
        matchWords(words, sb, "I We Me Us Myself Yourself Herself Themself", true);
        matchWords(words, sb, "Ourselves Yourselves Themselves My Our Hers Theirs Ours These", true);
        
        matchWords(words, sb, "Phenomenon Plane Tribal Vanguard", true);
        matchWords(words, sb, "Noninstant Nonphenomenon Nonplane Nonplaneswalker", true);
        matchWords(words, sb, "Nonscheme Nonsorcery Nontribal Nonvanguard", true);
        matchWords(words, sb, "Ongoing World Nonongoing Nonworld", true);
        
        matchWords(words, sb, "Planeswalkers Sorceries", true);
        matchWords(words, sb, "Token's Permanents' Tokens' Sources' Spells'", true);
    }
    
    private static void matchWords(Set<String> words, StringBuffer sb, String text, boolean extra) {
        sb.setLength(0);
        Matcher m = word.matcher(text.toLowerCase());
        while(m.find()) {
            m.appendReplacement(sb, "");
            if(m.group(3) != null) {
                if(!words.add(m.group()) && extra) {
                    System.err.println("duplicate word: " + m.group());
                }
            }
        }
        m.appendTail(sb);
        
        String rest = sb.toString().replaceAll("[ ,.;:+/0-9~()—\"-]", "");
        if(!rest.isEmpty()) System.out.println(rest + " <> " + text);
    }
}
